# Generated by Django 5.1 on 2024-09-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_progress_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcontent',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='topic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
