# Generated by Django 5.1 on 2024-10-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_textcontent_difficulty_level_textcontent_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('matching', 'Matching'), ('comprehension', 'Comprehension'), ('scramble', 'Scramble'), ('blanks', 'Blanks')], default='matching', max_length=100),
        ),
    ]
